name: Build CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-2019

    steps:
    - name: Checkout
      uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - name: Setup MSBuild.exe
      uses: microsoft/setup-msbuild@v2

    #- name: Compile app
    #  run: |
    #    msbuild /t:restore
    #    dotnet build
      
    - name: Build solution
      run: msbuild -t:rebuild -property:Configuration=Release